M48
; DRILL file {KiCad (6.0.7)} date Sun Sep 18 21:03:05 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-18T21:03:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X103.759Y-81.2
X104.775Y-86.28
X105.791Y-81.2
T2
X101.72Y-110.952
X125.92Y-110.952
T0
M30
